spring.application.name=HuynhLeHoan_22682941_Tuan01
# HOST
spring.data.redis.host=redis-19994.c244.us-east-1-2.ec2.cloud.redislabs.com

# PORT
spring.data.redis.port=19994

# PASSWORD
spring.data.redis.password=qyuEbI9rAAmmh3nnKK29TTW6PRcJQa4T