spring.application.name=CMS_LayredArchitechture

spring.datasource.url=jdbc:h2:mem:cmsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# B?t H2 Console ?? xem giao di?n web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console